projects:
  AmplifyAndroid:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: 52lshv2whzhexdpxzilxl7wdyu
      endpoints:
        prod: >-
          https://wd3rvn22xjb55bq5mwroc6iyqu.appsync-api.eu-central-1.amazonaws.com/graphql
